### ISSUE TITLE
Tested cheerio-cli for known vulnerabilities: Please could you upgrade dependency to newer cheerio ?

### ISSUE THREAD

**Issue by ainthek** [mlwmlw/cheerio-cli#2]
$ snyk test cheerio-cli

Testing cheerio-cli...

✗ Medium severity vulnerability found in lodash
  Description: Regular Expression Denial of Service (ReDoS)
  Info: https://snyk.io/vuln/SNYK-JS-LODASH-73639
  Introduced through: cheerio@0.19.0
  From: cheerio@0.19.0 > lodash@3.10.1

✗ Medium severity vulnerability found in lodash
  Description: Prototype Pollution
  Info: https://snyk.io/vuln/npm:lodash:20180130
  Introduced through: cheerio@0.19.0
  From: cheerio@0.19.0 > lodash@3.10.1

✗ High severity vulnerability found in lodash
  Description: Prototype Pollution
  Info: https://snyk.io/vuln/SNYK-JS-LODASH-450202
  Introduced through: cheerio@0.19.0
  From: cheerio@0.19.0 > lodash@3.10.1

✗ High severity vulnerability found in lodash
  Description: Prototype Pollution
  Info: https://snyk.io/vuln/SNYK-JS-LODASH-73638
  Introduced through: cheerio@0.19.0
  From: cheerio@0.19.0 > lodash@3.10.1

Organization:      ainthek
Package manager:   npm
Open source:       yes
Project path:      cheerio-cli

Tested cheerio-cli for known vulnerabilities, found 4 vulnerabilities, 4 vulnerable paths.

**Comment by mlwmlw** [comment]
Hello ainthek,

I have upgraded the package cheerio and publish the new version cheerio-cli to npm.

Thanks.
